# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
  AutoCorrect: true
  Exclude:
    - "config/**/*"
    - "db/migrate/**/*"
    - "db/schema.rb"
    - "spec/**/*"
    - "Rakefile"
    - "Gemfile"
    - "config.ru"
    - "bin/**/*"
    - "**/*.erb"

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/LineLength:
  Exclude:
    - "**/*.erb"
